export const SUGGESTIONS = [
  "All",
  "React",
  "JavaScript",
  "News",
  "Movies",
  "Trending",
  "Music",
  "Live",
  "Gaming",
  "Podcasts",
  "Books",
  "Education",
  "Comedy",
  "Taylor Swift",
  "Cooking",
  "Travel",
  "Fitness",
  "Technology",     
  "Science",  
  "Art",      
  "DIY",
  "Fashion",  
  "Sports",
  "Health",
  "Animals",
  "Nature",
  "Photography",
  "History",
];

export const OPTIONS = [
  "Our Data in YouTube",
  "Appearance: Device theme",
  "Language: English",
  "Restricted Mode: Off",
  "Location: Pakistan",
  "Keyboard shortcuts",
  "Settings",
  "Help",
  "Send feedback",
];